name: Debug Schemas and Configurations

on:
  workflow_dispatch:

jobs:
  debug-schemas:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all available schemes
        run: |
          echo "Listing all available schemes and configurations..."
          xcodebuild -list -workspace LoopWorkspace.xcworkspace
